### ISSUE TITLE
autojs

### ISSUE THREAD

**Issue by keep-an** [blackcd318/autojs4#1]

**Comment by keep-an** [comment]
PaddleOCR
https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/deploy/android_demo

**Comment by blackcd318** [comment]
我用邮件直接回复的不知道怎么没显示，我不知道你为什么要autojs添加ocr功能，感觉这功能不是很必须啊，你是要自动识别图片中的文字保存吗？要不可以直接用搜图找到坐标然后处理啊

**Comment by keep-an** [comment]
识别文字在某些地方可以用的到，识别了之后翻译，百度开源了paddleocr安卓项目，https://blog.csdn.net/QI971006/article/details/115294998我看了这个教程但是成功不了。大神能把他添加在autojs里面吗？

**Comment by keep-an** [comment]
hamibot把自己的ocr也换为PaddleOCR了

**Comment by blackcd318** [comment]
这样刚好合你的用法了
