### ISSUE TITLE
可以传一下对应的打包插件吗

### ISSUE THREAD

**Issue by huayangnw** [blackcd318/autojs4#3]
安装了Autojs4.1.1-alpha3-common-armeabi-v7a-release，可以正常使用和调试，不会再收到 “版本需要更新”的强制提示了， 但是没有对应的打包插件， 我有Autojs4.1.1-alpha2对应的打包插件，但安装上之后Autojs4.1.1-alpha3还是提示要下载打包插件

**Comment by blackcd318** [comment]
这个只是改了下版本号+1,代码基本上都是4.1.1alpha2的,不能打包可能是不是跟这次的强制更新有关,我没有用过这个打包,报什么错?

**Comment by blackcd318** [comment]
这个只是改了下版本号+1,代码基本上都是4.1.1alpha2的,不能打包可能是不是跟这次的强制更新有关,我没有用过这个打包,报什么错,我没事时看能不能解决

**Comment by blackcd318** [comment]
看了下代码,可能是打包插件的签名跟我这个修改过代码再打包的app的签名不一样的原因,我把验证签名的部分跳过去,一会上传,你看如果文件更新了就下载了试试(国内往github上传可能会挺慢)

**Comment by huayangnw** [comment]
也不算报错，就是提示没有安装插件，默认点安装会跳转到 autojspro的官网。 需要的话我可以发一下我手里有的 4.1.1alpha2.apk和配套的打包插件， 现在 4.1.1alpha2 采用卸载重装并且断网的方式还是可以勉强使用的

**Comment by huayangnw** [comment]
好嘞，等你的包。 下载不会慢，我墙过去了

**Comment by blackcd318** [comment]
碰运气的,有时候挺快的,有时候半天打不开

**Comment by huayangnw** [comment]
安装了刚刚上传的版本和打包插件，提示“打包插件版本过低，打包的应用可能无法正常运行……” ， 实际是插件不可以使用

**Comment by blackcd318** [comment]
你再试试,把你说的这部分验证也去掉了

**Comment by huayangnw** [comment]
不行哦， 提示“打包插件不可用” ， 方便的话你那边安装一下试试，可以选择demo的任意js——“更多”——“打包应用” ——“确定” 
 就能复现

**Comment by blackcd318** [comment]
你再试试,在我机子上可以了

**Comment by huayangnw** [comment]
可以了，打包成功，运行良好，非常感谢~

**Comment by gkongy** [comment]
> 这个只是改了下版本号+1,代码基本上都是4.1.1alpha2的,不能打包可能是不是跟这次的强制更新有关,我没有用过这个打包,报什么错,我没事时看能不能解决

我改了版本号还是弹出这个窗口，无奈只能不让它联网。请教改版本号需要改几个地方？

**Comment by gkongy** [comment]
> 这个只是改了下版本号+1,代码基本上都是4.1.1alpha2的,不能打包可能是不是跟这次的强制更新有关,我没有用过这个打包,报什么错,我没事时看能不能解决

我改了半天版本号没成功，最后去掉了它联网权限凑合着用。有空时指导指导改那几个地方。😃
